openapi: 3.2.0
info:
  license:
    name: GPL-v2.0
    url: http://www.gnu.org/licenses/gpl-2.0.txt
  version: 1.0.9
  title: Bonita BDM API
  description: 'Download OpenAPI specification

    Download Postman collection


    The REST API lets you access the data with HTTP requests; it is useful when implementing rich web forms / pages for a good user experience.'
  x-logo:
    url: images/ofelia-logo.svg
    backgroundColor: '#19465f'
    altText: Bonita API
    href: /
servers:
- url: http://localhost:8080/bonita
  description: Sample url for a local development server.
security:
- bonita_auth: []
  bonita_token: []
- bearer_auth: []
tags:
- name: BDM
  x-displayName: Business Data Model
  description: 'Show status or install or update the Business Data Model.


    Installing or updating a BDM needs to be done in two successive steps:


    1. Upload a BDM file

    2. Install/Update the previously uploaded file


    **To do this, the maintenance mode needs to be enabled.**


    **In Enterprise editions, if you have an access control file installed, you need to delete it before installing or updating your BDM.**'
paths:
  /API/bdm/businessData/{businessDataType}/findByIds:
    get:
      tags:
      - BDM
      summary: Finds business data By Ids
      description: Finds business data specified by their identifiers.
      operationId: searchBusinessDataByIds
      parameters:
      - description: Business Data Type
        in: path
        name: businessDataType
        required: true
        schema:
          type: string
          maxLength: 250
          pattern: ^[A-Za-z0-9\_\-\.]{0,250}$
        example: com.company.model.Employee
      - description: list of persistenceIds (comma separated)
        in: query
        name: ids
        required: true
        schema:
          type: string
          maxLength: 250
          pattern: ^[A-Za-z0-9\_\-\.]{0,250}$
        example: 1,3,56
      responses:
        '200':
          description: 'Success '
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BusinessData'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        5XX:
          $ref: '#/components/responses/ServerError'
  /API/bdm/businessData/{businessDataType}/{persistenceId}:
    get:
      tags:
      - BDM
      summary: Finds business data by Id
      description: Finds business data specified by its identifier.
      operationId: searchBusinessDataById
      parameters:
      - description: Business Data Type
        in: path
        name: businessDataType
        required: true
        schema:
          type: string
          maxLength: 250
          pattern: ^[A-Za-z0-9\_\-\.]{0,250}$
        example: com.company.model.Employee
      - description: Business data ID
        in: path
        name: persistenceId
        required: true
        schema:
          type: string
          maxLength: 250
          pattern: ^[A-Za-z0-9\_\-\.]{0,250}$
        example: 1
      responses:
        '200':
          description: 'Success '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessData'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        5XX:
          $ref: '#/components/responses/ServerError'
  /API/bdm/businessData/{businessDataType}/{persistenceId}/{attributeName}:
    get:
      tags:
      - BDM
      summary: Finds business data attribute by id
      description: Gets the business data attribute of business data according to its identifier and attribute name. Request url.
      operationId: searchBusinessDataAttributeById
      parameters:
      - description: Business Data Type
        in: path
        name: businessDataType
        required: true
        schema:
          type: string
          maxLength: 250
          pattern: ^[A-Za-z0-9\_\-\.]{0,250}$
        example: com.company.model.Employee
      - description: Business data ID
        in: path
        name: persistenceId
        required: true
        schema:
          type: string
          maxLength: 250
          pattern: ^[A-Za-z0-9\_\-\.]{0,250}$
        example: 1
      - description: Business data attribute name
        in: path
        name: attributeName
        required: true
        schema:
          type: string
          maxLength: 250
          pattern: ^[A-Za-z0-9\_\-\.]{0,250}$
        example: company
      responses:
        '200':
          description: 'Success '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessData'
              example:
                persistenceId_string: '1'
                persistenceVersion_string: '0'
                company: The Big Company
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        5XX:
          $ref: '#/components/responses/ServerError'
  /portal/fileUpload:
    post:
      tags:
      - BDM
      summary: Upload a file
      description: 'Upload file.


        **NOTE:** If this file is a BDM zip, to do this, Maintenance mode needs to be enabled.

        In Enterprise editions, if you have an access control file installed, you need to delete it before installing or updating your BDM.'
      operationId: uploadFile
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FileUploadRequest'
      responses:
        '200':
          description: 'Success: the temp file name as present on the server'
          content:
            text/plain:
              schema:
                type: string
                maxLength: 250
                pattern: ^[A-Za-z0-9\_\-\.]{0,250}$
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        5XX:
          $ref: '#/components/responses/ServerError'
  /API/tenant/bdm:
    get:
      tags:
      - BDM
      summary: Get the BDM
      description: Returns the current BDM. Make this call to get the status the BDM.
      operationId: getBdm
      responses:
        '200':
          description: 'Success '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bdm'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        5XX:
          $ref: '#/components/responses/ServerError'
    post:
      tags:
      - BDM
      summary: Install a BDM
      deprecated: true
      description: 'Install a BDM


        Warning: as of 9.0.0, importing a BDM using this API is deprecated.'
      operationId: installBDM
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BDMInstallRequest'
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        5XX:
          $ref: '#/components/responses/ServerError'
components:
  responses:
    Unauthorized:
      description: Authorization information is missing or invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Unauthorized
    OK:
      description: OK
    NotFound:
      description: The resource for the specified ID was not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Resource not found.
    Forbidden:
      description: Forbidden, The request contained valid data and was understood by the server, but the server is refusing action.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Forbidden, The request contained valid data and was understood by the server, but the server is refusing action.
    BadRequest:
      description: Bad request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Bad request
    ServerError:
      description: Unexpected error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: An unexpected error occured.
  schemas:
    FileUploadRequest:
      type: object
      description: The file to upload
      properties:
        file:
          type: string
          format: binary
    Bdm:
      type: object
      description: ''
      properties:
        id:
          description: BDM id
          type: string
        name:
          description: BDM name
          type: string
        type:
          description: BDM type
          type: string
        state:
          $ref: '#/components/schemas/TenantResourceState'
        lastUpdatedBy:
          description: This value is always -1 because only the technical admin can install BDM.
          type: string
          default: '-1'
        lastUpdateDate:
          description: Last date when the BDM was installed or updated.
          type: string
      example:
        id: '309'
        name: client_bdm.zip
        type: BDM
        state: INSTALLED
        lastUpdatedBy: -1
        lastUpdateDate: '2018-01-17T17:05:36.671Z'
    Error:
      type: object
      additionalProperties: true
      properties:
        message:
          type: string
          description: The error message
        exception:
          type: string
          description: The exception type
        explanations:
          description: Further details on the error
          type: array
          items:
            type: string
    BDMInstallRequest:
      type: object
      properties:
        fileUpload:
          type: string
          description: the temporary file name once uploaded on the server
      example:
        fileUpload: tmp_uploaded_bdm.zip
    TenantResourceState:
      description: Tenant resource state (BDM, BDM access control, ...)
      type: string
      enum:
      - INSTALLING
      - INSTALLED
    BusinessData:
      type: object
      additionalProperties: true
      description: "Retrieve business data value. Depending on the object attribute loading policy,\nthe API returns either the full object in JSON representation or the HATEOAS links to the object attributes.\n\nLong attributes use a string representation added in 7.0.1 as a workaround for the JavaScript integer spectrum issue.\n\nRepresentation of object attributes with an _always load_ policy:\n\n```json\n{\n  \"persistenceId\": _number_, // <-- deprecated\n  \"persistenceId_string\": \"_number_\"\n  \"persistenceVersion\": _number_, // <-- deprecated\n  \"persistenceVersion_string\": \"_number_\"\n  \"attributeName\":_attributeType_\n  ...\n}\n```\n\nThe string representation added in 7.0.1 for Long attributes is a workaround for the JavaScript integer spectrum issue.\n\nHATEOAS representation of object attribute with a _load when needed_ policy:\n```json\n\"links\":[\n   {\n   \"rel\":_string_\n   \"href\":_uri_\n   }\n]\n```\n"
      properties:
        persistenceId_string:
          description: Id of the business data object
          type: string
        persistenceVersion_string:
          description: Version of the business data object instance
          type: string
      example:
        persistenceId_string: '1'
        persistenceVersion_string: '0'
        contractName: contract for Netcom3
        terms:
        - persistenceId: 1
          persistenceId_string: '1'
          persistenceVersion: 0
          persistenceVersion_string: '0'
          termName: term Name
        - persistenceId: 2
          persistenceId_string: '2'
          persistenceVersion: 0
          persistenceVersion_string: '0'
          termName: term Name
        client:
          persistenceId: 13
          persistenceId_string: '13'
          persistenceVersion: 0
          persistenceVersion_string: '0'
          clientName: client name
          description: n/a
          industry:
          - persistenceId: 2
            persistenceId_string: '2'
            persistenceVersion: 0
            persistenceVersion_string: '0'
            industryName: Services
          - persistenceId: 3
            persistenceId_string: '3'
            persistenceVersion: 0
            persistenceVersion_string: '0'
            industryName: Software
  securitySchemes:
    bonita_auth:
      name: JSESSIONID
      description: 'To call the REST API, you must first log on with a user registered in the Engine database. Please refer to the __[Login API](#operation/login)__ operations section.

        '
      type: apiKey
      in: cookie
    bonita_token:
      name: X-Bonita-API-Token
      description: 'To call the REST API, you must first log on with a user registered in the Engine database. Please refer to the __[Login API](#operation/login)__ operations section.

        '
      type: apiKey
      in: header
    bearer_auth:
      description: '![edition](https://img.shields.io/badge/edition-entreprise-blue)


        When Bonita runtime is configured for SSO with openID Connect it is possible To call the REST API directly with a Bearer Authorization header containing the access token.

        '
      type: http
      scheme: bearer
x-tagGroups:
- name: Authentication
  tags:
  - Authentication
  - PlatformAuthentication
- name: Application
  tags:
  - Application
  - ApplicationMenu
  - ApplicationPage
  - FormMapping
- name: BDM
  tags:
  - BDM
  - BusinessDataQuery
  - Business Data Operations
  - BDMAccessControl
  - DataRetention
- name: BPM
  tags:
  - Activity
  - ArchivedActivity
  - HumanTask
  - ManualTask
  - Task
  - UserTask
  - ArchivedHumanTask
  - ArchivedManualTask
  - ArchivedTask
  - ArchivedUserTask
  - ActivityVariable
  - ArchivedActivityVariable
  - ProcessInstanceVariable
  - ArchivedProcessInstanceVariable
  - ProcessInstanceDocument
  - ArchivedProcessInstanceDocument
  - Actor
  - ActorMember
  - ProcessInstance
  - ArchivedProcessInstance
  - ProcessInstanceInfo
  - ProcessInstanceComment
  - ArchivedProcessInstanceComment
  - Process
  - Diagram
  - ProcessInfo
  - ProcessParameter
  - ProcessResolutionProblem
  - ProcessSupervisor
  - ProcessConnectorDependency
  - ConnectorFailure
  - ConnectorInstance
  - ArchivedConnectorInstance
  - FlowNode
  - ArchivedFlowNode
  - Failure
  - ArchivedFailure
  - TimerEventTrigger
  - Message
  - Signal
  - Delegation
- name: Custom user info
  tags:
  - CustomUserDefinition
  - CustomUserValue
  - CustomUser
- name: Identity
  tags:
  - ProfessionalContactData
  - Group
  - Membership
  - Role
  - User
  - Authentication
- name: Platform
  tags:
  - PlatformAuthentication
  - Platform
  - License
  - Information
- name: Portal
  tags:
  - Page
  - Profile
  - ProfileEntry
  - ProfileMember
  - Theme
  - Upload
- name: System
  tags:
  - I18nlocale
  - I18ntranslation
  - Log
  - Session
  - Maintenance
- name: Other
  tags:
  - RestAPIextensions
- name: Upload
  tags:
  - FormFileUpload
