openapi: 3.2.0
info:
  license:
    name: GPL-v2.0
    url: http://www.gnu.org/licenses/gpl-2.0.txt
  version: 1.0.9
  title: Bonita Failure API
  description: 'Download OpenAPI specification

    Download Postman collection


    The REST API lets you access the data with HTTP requests; it is useful when implementing rich web forms / pages for a good user experience.'
  x-logo:
    url: images/ofelia-logo.svg
    backgroundColor: '#19465f'
    altText: Bonita API
    href: /
servers:
- url: http://localhost:8080/bonita
  description: Sample url for a local development server.
security:
- bonita_auth: []
  bonita_token: []
- bearer_auth: []
tags:
- name: Failure
  x-displayName: BPM Failure
  description: 'Failure leading a BPM entity instance to a failed state

    This Web REST API is available in **Enterprise editions only**, since version 10.3 (2025.1).'
paths:
  /API/bpm/failure/flowNode/{flowNodeInstanceId}:
    get:
      tags:
      - Failure
      summary: Retrieve the failures of a flownode instance by it's ID
      description: '!edition


        Returns the most recent failures for the given flownode ID'
      operationId: getBPMFailuresByFlowNodeInstanceId
      parameters:
      - description: The identifier of the flownode instance from which to retrieve the failures
        in: path
        name: flowNodeInstanceId
        required: true
        schema:
          type: string
          maxLength: 250
          pattern: ^[0-9\_\-\.]{0,250}$
      - $ref: '#/components/parameters/pageCount'
      responses:
        '200':
          description: 'Success '
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BPMFailure'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        5XX:
          $ref: '#/components/responses/ServerError'
  /API/bpm/failure/case/{caseId}:
    get:
      tags:
      - Failure
      summary: Retrieve the failures of a case (process instance) by it's ID
      description: '!edition


        Returns the most recent failures for the given case'
      operationId: getBPMFailuresByCaseId
      parameters:
      - description: The identifier of the case from which to retrieve the failures
        in: path
        name: caseId
        required: true
        schema:
          type: string
          maxLength: 250
          pattern: ^[0-9\_\-\.]{0,250}$
      - $ref: '#/components/parameters/pageCount'
      responses:
        '200':
          description: 'Success '
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BPMFailure'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        5XX:
          $ref: '#/components/responses/ServerError'
  /API/bpm/achivedFailure/case/{caseId}:
    get:
      tags:
      - Failure
      summary: Retrieve the archived failures of an archived case (process instance) by it's…
      description: '!edition


        Returns the most recent archived failures for the given archived case sourceObjectID'
      operationId: getArchivedBPMFailuresByCaseId
      parameters:
      - description: The original identifier (sourceObjectID) of the case from which to retrieve the failures
        in: path
        name: caseId
        required: true
        schema:
          type: string
          maxLength: 250
          pattern: ^[0-9\_\-\.]{0,250}$
      - $ref: '#/components/parameters/pageCount'
      responses:
        '200':
          description: 'Success '
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ArchivedBPMFailure'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        5XX:
          $ref: '#/components/responses/ServerError'
  /API/bpm/failure/case/{rootCaseId}/childCases:
    get:
      tags:
      - Failure
      summary: Retrieve the failures of the child cases of a root case (process instance) by…
      description: '!edition


        Returns the most recent failures among all the child cases (started by call activities) of a case'
      operationId: getBPMFailuresByRootCaseId
      parameters:
      - description: The identifier of the root case from which to retrieve the failures (its sourceObjectID if the root case is archived)
        in: path
        name: rootCaseId
        required: true
        schema:
          type: string
          maxLength: 250
          pattern: ^[0-9\_\-\.]{0,250}$
      - $ref: '#/components/parameters/pageCount'
      responses:
        '200':
          description: 'Success '
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BPMFailure'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        5XX:
          $ref: '#/components/responses/ServerError'
  /API/bpm/achivedFailure/case/{rootCaseId}/childCases:
    get:
      tags:
      - Failure
      summary: Retrieve the archived failures of the archived child cases of a root case…
      description: '!edition


        Returns the most recent archived failures among all the archived child cases (started by call activities) of a case'
      operationId: getArchivedBPMFailuresByRootCaseId
      parameters:
      - description: The identifier of the root case from which to retrieve the archived failures (its sourceObjectID if the root case is archived)
        in: path
        name: rootCaseId
        required: true
        schema:
          type: string
          maxLength: 250
          pattern: ^[0-9\_\-\.]{0,250}$
      - $ref: '#/components/parameters/pageCount'
      responses:
        '200':
          description: 'Success '
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ArchivedBPMFailure'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        5XX:
          $ref: '#/components/responses/ServerError'
components:
  parameters:
    pageCount:
      description: maximum number of elements to retrieve
      explode: true
      in: query
      name: c
      example: '10'
      required: true
      schema:
        type: integer
        minimum: 1
        default: 20
        format: int32
      style: form
  responses:
    Unauthorized:
      description: Authorization information is missing or invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Unauthorized
    BadRequest:
      description: Bad request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Bad request
    NotFound:
      description: The resource for the specified ID was not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Resource not found.
    Forbidden:
      description: Forbidden, The request contained valid data and was understood by the server, but the server is refusing action.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Forbidden, The request contained valid data and was understood by the server, but the server is refusing action.
    ServerError:
      description: Unexpected error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: An unexpected error occured.
  schemas:
    BPMFailure:
      type: object
      description: A failure that happened during a BPM instance (flow node, process) execution that led to the instance being in a failed state.
      properties:
        caseId:
          description: the id of the process instance in which that failure occurred
          type: string
        rootCaseId:
          description: the id of the root process instance in which that failure occurred
          type: string
        context:
          description: Context of the failure
          type: string
        errorMessage:
          description: the message of the exception
          type: string
        failureDate:
          description: the date when the failure occurred in milliseconds since epoch
          type: string
        flowNodeInstanceId:
          description: the id of the flow node instance in which the failure occurred
          type: string
        id:
          description: the failure id
          type: string
        processDefinitionId:
          description: the process id that is associated with the flow node or case instance of the failure
          type: string
        scope:
          description: the scope of the failure (General information, Operation, Event, Iteration, Connector, Data initialization, Actor mapping, Outgoing transition, or UNKNOWN)
          type: string
        stackTrace:
          description: the stack trace of the exception
          type: string
      example:
        caseId: '2'
        rootCaseId: '1'
        context: expression::setvariable_decision
        errorMessage: Error while executing operations
        failureDate: '1732564534177'
        flowNodeInstanceId: '70'
        id: '456'
        processDefinitionId: '45'
        scope: Operation
        stackTrace: Exception in thread 'main' org.bonitasoft.engine.core.process.instance.api.exceptions.SActivityStateExecutionException
    Error:
      type: object
      additionalProperties: true
      properties:
        message:
          type: string
          description: The error message
        exception:
          type: string
          description: The exception type
        explanations:
          description: Further details on the error
          type: array
          items:
            type: string
    ArchivedBPMFailure:
      type: object
      description: The archived version of a failure that happened during a BPM instance (flow node, process) execution that led to the instance being in a failed state.
      properties:
        archivedDate:
          type: string
          description: the date when this failure was archived, in milliseconds since epoch
        caseId:
          description: the id of the process instance in which that failure occurred
          type: string
        rootCaseId:
          description: the id of the root process instance in which that failure occurred
          type: string
        context:
          description: Context of the failure
          type: string
        errorMessage:
          description: the message of the exception
          type: string
        failureDate:
          description: the date when the failure occurred in milliseconds since epoch
          type: string
        flowNodeInstanceId:
          description: the id of the flow node instance in which the failure occurred
          type: string
        id:
          description: the archived failure id
          type: string
        processDefinitionId:
          description: the process id that is associated with the flow node or case instance of the failure
          type: string
        scope:
          description: the scope of the failure (General information, Operation, Event, Iteration, Connector, Data initialization, Actor mapping, Outgoing transition, or UNKNOWN)
          type: string
        sourceObjectId:
          type: string
          description: the original id of the failure before it was archived
        stackTrace:
          description: the stack trace of the exception
          type: string
      example:
        archivedDate: '1732564904376'
        caseId: '10'
        rootCaseId: '9'
        context: expression::setvariable_decision
        errorMessage: Error while executing operations
        failureDate: '1732564534177'
        flowNodeInstanceId: '70'
        id: '456'
        processDefinitionId: '45'
        scope: Operation
        sourceObjectId: '23'
        stackTrace: Exception in thread 'main' org.bonitasoft.engine.core.process.instance.api.exceptions.SActivityStateExecutionException
  securitySchemes:
    bonita_auth:
      name: JSESSIONID
      description: 'To call the REST API, you must first log on with a user registered in the Engine database. Please refer to the __[Login API](#operation/login)__ operations section.

        '
      type: apiKey
      in: cookie
    bonita_token:
      name: X-Bonita-API-Token
      description: 'To call the REST API, you must first log on with a user registered in the Engine database. Please refer to the __[Login API](#operation/login)__ operations section.

        '
      type: apiKey
      in: header
    bearer_auth:
      description: '![edition](https://img.shields.io/badge/edition-entreprise-blue)


        When Bonita runtime is configured for SSO with openID Connect it is possible To call the REST API directly with a Bearer Authorization header containing the access token.

        '
      type: http
      scheme: bearer
x-tagGroups:
- name: Authentication
  tags:
  - Authentication
  - PlatformAuthentication
- name: Application
  tags:
  - Application
  - ApplicationMenu
  - ApplicationPage
  - FormMapping
- name: BDM
  tags:
  - BDM
  - BusinessDataQuery
  - Business Data Operations
  - BDMAccessControl
  - DataRetention
- name: BPM
  tags:
  - Activity
  - ArchivedActivity
  - HumanTask
  - ManualTask
  - Task
  - UserTask
  - ArchivedHumanTask
  - ArchivedManualTask
  - ArchivedTask
  - ArchivedUserTask
  - ActivityVariable
  - ArchivedActivityVariable
  - ProcessInstanceVariable
  - ArchivedProcessInstanceVariable
  - ProcessInstanceDocument
  - ArchivedProcessInstanceDocument
  - Actor
  - ActorMember
  - ProcessInstance
  - ArchivedProcessInstance
  - ProcessInstanceInfo
  - ProcessInstanceComment
  - ArchivedProcessInstanceComment
  - Process
  - Diagram
  - ProcessInfo
  - ProcessParameter
  - ProcessResolutionProblem
  - ProcessSupervisor
  - ProcessConnectorDependency
  - ConnectorFailure
  - ConnectorInstance
  - ArchivedConnectorInstance
  - FlowNode
  - ArchivedFlowNode
  - Failure
  - ArchivedFailure
  - TimerEventTrigger
  - Message
  - Signal
  - Delegation
- name: Custom user info
  tags:
  - CustomUserDefinition
  - CustomUserValue
  - CustomUser
- name: Identity
  tags:
  - ProfessionalContactData
  - Group
  - Membership
  - Role
  - User
  - Authentication
- name: Platform
  tags:
  - PlatformAuthentication
  - Platform
  - License
  - Information
- name: Portal
  tags:
  - Page
  - Profile
  - ProfileEntry
  - ProfileMember
  - Theme
  - Upload
- name: System
  tags:
  - I18nlocale
  - I18ntranslation
  - Log
  - Session
  - Maintenance
- name: Other
  tags:
  - RestAPIextensions
- name: Upload
  tags:
  - FormFileUpload
